server:
  applicationConnectors:
    - type: http
      port: 7798
  rootPath: /
  adminConnectors:
    - type: http
      port: 7799
  adminContextPath: /admin
      
swagger:
  title: CONTACT
  description: Contact Service
  resourcePackage: com.cntct.resource

database:
  driverClass: com.mysql.cj.jdbc.Driver
  user: root
  password: pass
  url: jdbc:mysql://localhost:3306/notification
  properties:
    charSet: UTF-8
  maxWaitForConnection: 1s
  validationQuery: "/* MyService Health Check */ SELECT 1"
  validationQueryTimeout: 3s
  minSize: 8
  maxSize: 32
  checkConnectionWhileIdle: false
  evictionInterval: 10s
  minIdleTime: 1 minute

logging:
  loggers:
    org.hibernate.SQL: TRACE
      
#logging:
#  level: INFO
#  loggers:
#    org.hibernate.ejb.HibernatePersistence: ERROR
#  appenders:
#  - type: file
#    threshold: ALL
#    timeZone: IST
#    logFormat: "%-5p [%d{ISO8601}] [%X{reqId} %X{txnId}] %c{1.}: %m\n%ex"
#    currentLogFilename: /var/log/nighly/server.log
#    archive: true
#    archivedLogFilenamePattern: /var/log/nighly/server-%d.log.gz
#    archivedFileCount: 5